spring:
  jackson:
    time-zone: Asia/Seoul

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

logging:
  level:
    root: INFO