services:

  test-service:
    build:
      context: ..
      dockerfile: docker/Dockerfiles/test-service.Dockerfile
      args:
        JAR_FILE: services/test-service/build/libs/*.jar

    container_name: test-service

    ports:
      - "9000:9000"

    networks:
      - delivery-network

  auth-service:
    build:
      context: ..
      dockerfile: docker/Dockerfiles/auth-service.Dockerfile
      args:
        JAR_FILE: services/auth-service/build/libs/*.jar

    env_file:
      - ../.env

    container_name: auth-service

    networks:
      - delivery-network

  user-service:
    build:
      context: ..
      dockerfile: docker/Dockerfiles/user-service.Dockerfile
      args:
        JAR_FILE: services/user-service/build/libs/*.jar

    env_file:
      - ../.env

    container_name: user-service

    networks:
      - delivery-network

networks:
  delivery-network:
    external: true