server:
  port: 8888


spring:
  application:
    name: config-service


  cloud:
    config:
      server:
        git:
          uri: https://github.com/rvbear/delivery-platform
          default-label: main
          search-paths: config-repo